[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_usdc_presale = "FdyQCcfJRbCZEnT19MZM5VMPpmnEaGJFb75YLcCWmR6s"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
