[features]
seeds = false
skip-lint = false

[programs.localnet]
token_presale = "2g4jbSt1Z7PDYfRHKVXo38h75a7FcRsqxK9NVH7uusJu"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
